FROM rwlab/javajdk8:u131
MAINTAINER Roderick Warren  <roderickwarren76@gmail.com>

RUN mkdir /usr/local/jetty

COPY jetty-distribution-9.4.6.v20170531.tar.gz /usr/local/jetty/jetty-distribution-9.4.6.v20170531.tar.gz

RUN cd /usr/local/jetty; \
        tar --no-same-owner -zxvpf jetty-distribution-9.4.6.v20170531.tar.gz; \
        rm jetty-distribution-9.4.6.v20170531.tar.gz

COPY start.ini /usr/local/jetty/jetty-distribution-9.4.6.v20170531/start.ini
