FROM rwlab/jb1:base
MAINTAINER Roderick Warren  <roderickwarren76@gmail.com>
WORKDIR /usr/local/jetty/jetty-distribution-9.4.6.v20170531/
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
CMD java -jar start.jar
